version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GI-PMS-wo_docker
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html/GI-PMS-wo
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: GI-PMS-wo-db_docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gl0b4l1nd0@2025
      MYSQL_DATABASE: pms
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    name: pms